export const categories = [
  {
    slug: "flour",
    name: "Flours & Mixes",
    nameMarathi: "पीठ व भाजणी",
    description: "Stone-ground traditional flours for every Indian dish",
    descriptionMarathi: "प्रत्येक पदार्थासाठी पारंपरिक पद्धतीने दगडावर दळलेले पीठ",
    emoji: "🌾",
    color: "from-amber-50 to-orange-100",
    border: "border-orange-200",
    image: "/products/upvas-bhajani-200-new.png",
  },
  {
    slug: "chatni",
    name: "Chutneys",
    nameMarathi: "चटणी",
    description: "Authentic dry chutneys packed with flavour",
    descriptionMarathi: "चविष्ट आणि खमंग अशा घरगुती सुक्या चटण्या",
    emoji: "🌶️",
    color: "from-red-50 to-rose-100",
    border: "border-rose-200",
    image: "/products/shengdana-chatni-new.png",
  },
  {
    slug: "mukhwas",
    name: "Mukhwas",
    nameMarathi: "मुखवास",
    description: "Natural mouth fresheners & digestive seeds",
    descriptionMarathi: "नैसर्गिक मुखशुद्धी व पचनास उपयुक्त बिया",
    emoji: "🌿",
    color: "from-green-50 to-emerald-100",
    border: "border-emerald-200",
    image: "/products/mukhwas-sauf-til-new2.png",
  },
  {
    slug: "sweets",
    name: "Sweet Dishes",
    nameMarathi: "स्वीट डिश",
    description: "Traditional Maharashtrian sweets & festive treats",
    descriptionMarathi: "पारंपरिक महाराष्ट्रीयन मिठाई व सणासुदीचे पदार्थ",
    emoji: "🍯",
    color: "from-yellow-50 to-amber-100",
    border: "border-amber-200",
    image: "/products/besan-ladoo-new.png",
  },
  {
    slug: "snacks",
    name: "Snacks & Timepass",
    nameMarathi: "टाईमपास",
    description: "Crispy, spicy ready-to-eat snacks",
    descriptionMarathi: "कुरकुरीत व चटपटीत तयार खाऊ पदार्थ",
    emoji: "🥨",
    color: "from-orange-50 to-yellow-100",
    border: "border-yellow-200",
    image: "/products/bhadang.png",
  },
  {
    slug: "masala",
    name: "Masalas & Spices",
    nameMarathi: "मसाला",
    description: "Aromatic spice blends & seasoning powders",
    descriptionMarathi: "सुगंधी मसाले व चवदार पदार्थ",
    emoji: "🫙",
    color: "from-red-50 to-orange-100",
    border: "border-orange-200",
    image: "/products/kala-masala-new.png",
  },
];

export const products = [
  // ── FLOURS & BHAJANI ──────────────────────────────────────────────────────
  {
    id: 1,
    slug: "shabudana-pith",
    name: "Shabudana Pith",
    nameMarathi: "शाबुदाना पीठ",
    category: "flour",
    ingredients: "Sabudana (Sago Seeds)",
    ingredientsMarathi: "साबुदाणा",
    usage: "Ladoo, papad, thalipeeth",
    usageMarathi: "लाडू, पापड, थालीपीठ",
    description: "Made from roasted sabudana. Perfect for fasting recipes – ladoo, papad and thalipeeth.",
    descriptionMarathi: "भाजलेल्या साबुदाण्यापासून तयार केलेले. उपवासाच्या पदार्थांसाठी उत्तम – लाडू, पापड व थालीपीठ.",
    variants: [{ weight: "200g", price: 50 }],
    featured: true,
    shelfLife: "3 months",
    recipe: "Mix one small spoon of crushed roasted peanuts, powdered sugar (to taste), and half a cup of lukewarm ghee into Bhagwati Shabudana Pith, blend well, and shape into delicious ladoos.",
    recipeMarathi: "एक छोटा चमचा भाजलेले शेंगदाणे कुट, पिठी साखर (आवडीप्रमाणे), अर्धा कप कोमट तूप हे सर्व साहित्य भगवती साबुदाणा पीठात एकत्र मिसळून घ्या आणि चविष्ट लाडू बनवा.",
    emoji: "🤍",
    image: "/products/shabudana-pith-new.png",
  },
  {
    id: 2,
    slug: "bhagar-pith-200",
    name: "Bhagar Pith",
    nameMarathi: "भगर पीठ",
    category: "flour",
    ingredients: "Bhagar / Varai (Barnyard Millet)",
    ingredientsMarathi: "भगर / वरई",
    usage: "Dosa, bhakri, puri",
    usageMarathi: "डोसा, भाकरी, पुरी",
    description: "Stone-ground barnyard millet flour ideal for crispy dosas and bhakri during fasting days.",
    descriptionMarathi: "उपवासाच्या दिवसांसाठी दगडावर दळलेले भगर पीठ – कुरकुरीत डोसा व भाकरीसाठी उत्तम.",
    variants: [{ weight: "200g", price: 45 }],
    featured: true,
    shelfLife: "3 months",
    recipe: "Mix Bhagwati Bhagar Pith with buttermilk into a dosa-like batter and let it rest for half an hour. Add salt to taste, then pour onto a hot greased tawa to make a dosa. Tastes wonderful with hot dosa and dry potato bhaji. You can also make puris from Bhagwati Bhagar Pith — delicious with dry potato bhaji.",
    recipeMarathi: "भगवती भगरपीठ आणि ताक एकत्र करून दोस्यासारखे पीठ बनवून अर्धा तास भिजत ठेवा. नंतर चवीनुसार मीठ टाकून गरम तव्यावर तूप सोडून भिजवलेल्या पिठाचा दोसा बनवा. गरम दोसा व सुकी बटाटा भाजी छान लागते. भगवती भगर पिठापासून तुम्ही पुऱ्या ही करू शकता. सुकी बटाटा भाजी सोबत चविष्ट लागते.",
    emoji: "🌾",
    image: "/products/bhagar-pith-200-new.png",
  },
  {
    id: 3,
    slug: "bhagar-pith-500",
    name: "Bhagar Pith (Large)",
    nameMarathi: "भगर पीठ (५०० ग्रॅम)",
    category: "flour",
    ingredients: "Bhagar / Varai (Barnyard Millet)",
    ingredientsMarathi: "भगर / वरई",
    usage: "Dosa, bhakri, puri",
    usageMarathi: "डोसा, भाकरी, पुरी",
    description: "Stone-ground barnyard millet flour in economy 500g pack – crispy dosas and bhakri.",
    descriptionMarathi: "दगडावर दळलेले भगर पीठ ५०० ग्रॅमच्या किफायतशीर पॅकमध्ये – कुरकुरीत डोसा व भाकरीसाठी.",
    variants: [{ weight: "500g", price: 85 }],
    featured: false,
    shelfLife: "3 months",
    recipe: "Mix Bhagwati Bhagar Pith with buttermilk into a dosa-like batter and let it rest for half an hour. Add salt to taste, then pour onto a hot greased tawa to make a dosa. Tastes wonderful with hot dosa and dry potato bhaji. You can also make puris from Bhagwati Bhagar Pith — delicious with dry potato bhaji.",
    recipeMarathi: "भगवती भगरपीठ आणि ताक एकत्र करून दोस्यासारखे पीठ बनवून अर्धा तास भिजत ठेवा. नंतर चवीनुसार मीठ टाकून गरम तव्यावर तूप सोडून भिजवलेल्या पिठाचा दोसा बनवा. गरम दोसा व सुकी बटाटा भाजी छान लागते. भगवती भगर पिठापासून तुम्ही पुऱ्या ही करू शकता. सुकी बटाटा भाजी सोबत चविष्ट लागते.",
    emoji: "🌾",
    image: "/products/bhagar-pith-500-new.png",
  },
  {
    id: 4,
    slug: "rajgira-pith-200",
    name: "Rajgira Pith",
    nameMarathi: "राजगीरा पीठ",
    category: "flour",
    ingredients: "Rajgira (Amaranth)",
    ingredientsMarathi: "राजगिरा",
    usage: "Puri (sweet & spicy)",
    usageMarathi: "पुरी (गोड व तिखट)",
    description: "Gluten-free amaranth flour great for puris – both spicy and sweet varieties.",
    descriptionMarathi: "ग्लूटेनमुक्त राजगिरा पीठ – गोड व तिखट पुरीसाठी उत्तम.",
    variants: [{ weight: "200g", price: 50 }],
    featured: true,
    shelfLife: "3 months",
    recipe: "Mix crushed green chillies (to taste) and salt (to taste) into Bhagwati Rajgira Pith, soak in buttermilk, and after ten minutes roll into puris and deep-fry in ghee or peanut oil. You can also make both plain and sweet puris from this flour.",
    recipeMarathi: "वाटलेली हिरवी मिरची (चवीप्रमाणे) मीठ (चवीप्रमाणे) भगवती राजगिरा पिठात एकत्र करून ताकात भिजवा आणि दहा मिनिटांनी पुरी लाटून तुपात किंवा शेंगदाणा तेलात तळून घ्या. या पिठाच्या तुम्ही साध्या आणि गोड पुऱ्याही बनवू शकता.",
    emoji: "🌿",
    image: "/products/rajgira-pith-200-new.png",
  },
  {
    id: 5,
    slug: "rajgira-pith-500",
    name: "Rajgira Pith (Large)",
    nameMarathi: "राजगीरा पीठ (५०० ग्रॅम)",
    category: "flour",
    ingredients: "Rajgira (Amaranth)",
    ingredientsMarathi: "राजगिरा",
    usage: "Puri (sweet & spicy)",
    usageMarathi: "पुरी (गोड व तिखट)",
    description: "Economy 500g pack of gluten-free amaranth flour for puris and fasting dishes.",
    descriptionMarathi: "उपवासाच्या पदार्थांसाठी व पुरीसाठी ग्लूटेनमुक्त राजगिरा पिठाचा ५०० ग्रॅमचा किफायतशीर पॅक.",
    variants: [{ weight: "500g", price: 105 }],
    featured: false,
    shelfLife: "3 months",
    recipe: "Mix crushed green chillies (to taste) and salt (to taste) into Bhagwati Rajgira Pith, soak in buttermilk, and after ten minutes roll into puris and deep-fry in ghee or peanut oil. You can also make both plain and sweet puris from this flour.",
    recipeMarathi: "वाटलेली हिरवी मिरची (चवीप्रमाणे) मीठ (चवीप्रमाणे) भगवती राजगिरा पिठात एकत्र करून ताकात भिजवा आणि दहा मिनिटांनी पुरी लाटून तुपात किंवा शेंगदाणा तेलात तळून घ्या. या पिठाच्या तुम्ही साध्या आणि गोड पुऱ्याही बनवू शकता.",
    emoji: "🌿",
    image: "/products/rajgira-pith-500-new.png",
  },
  {
    id: 6,
    slug: "upvas-bhajani-200",
    name: "Upvas Bhajani",
    nameMarathi: "उपवास भाजणी",
    category: "flour",
    ingredients: "Rajgira, Sabudana, Bhagar, Jeera",
    ingredientsMarathi: "राजगिरा, साबुदाणा, भगर, जिरे",
    usage: "Thalipeeth (fasting)",
    usageMarathi: "थालीपीठ (उपवास)",
    description: "A perfect fasting-day mix of four roasted ingredients for soft, golden thalipeeth.",
    descriptionMarathi: "उपवासाच्या दिवसासाठी चार भाजलेल्या पदार्थांचे मिश्रण – मऊसूत, सोनसळी थालीपीठासाठी.",
    variants: [{ weight: "200g", price: 54 }],
    featured: true,
    shelfLife: "3 months",
    recipe: "Mash two small boiled potatoes and mix in a spoon of crushed peanuts, salt, and crushed green chillies or red chilli powder (to taste) with Bhagwati Upvas Bhajani. Knead well with a little water or buttermilk and let it rest for 5 minutes. Cook on a tawa with ghee on both sides until golden and crisp. This thalipeeth tastes wonderful with butter or curd.",
    recipeMarathi: "दोन लहान आकाराचे बटाटे (उकडून बारीक केलेले) एक चमचा शेंगदाण्याचा कुट, मीठ, वाटलेल्या हिरव्या मिरच्या किंवा लाल तिखट (चवीप्रमाणे) हे सर्व साहित्य भगवती उपवास भाजणीत मिसळून थोडे पाणी किंवा ताक यात चांगले मळून घ्या आणि पाच मिनिटे भिजवून घ्या. तव्यावर सगळीकडून तूप सोडून दोन्ही बाजूने सोनेरी रंगावर खरपूस भाजून घ्या. लोणी किंवा दही यासोबत हे थालीपीठ छान लागते.",
    emoji: "🥞",
    image: "/products/upvas-bhajani-200-new.png",
  },
  {
    id: 7,
    slug: "upvas-bhajani-500",
    name: "Upvas Bhajani (Large)",
    nameMarathi: "उपवास भाजणी (५०० ग्रॅम)",
    category: "flour",
    ingredients: "Rajgira, Sabudana, Bhagar, Jeera",
    ingredientsMarathi: "राजगिरा, साबुदाणा, भगर, जिरे",
    usage: "Thalipeeth (fasting)",
    usageMarathi: "थालीपीठ (उपवास)",
    description: "Economy 500g pack of our popular Upvas Bhajani – perfect for frequent fasting families.",
    descriptionMarathi: "आमच्या लोकप्रिय उपवास भाजणीचा ५०० ग्रॅमचा किफायतशीर पॅक – वारंवार उपवास करणाऱ्या कुटुंबांसाठी उत्तम.",
    variants: [{ weight: "500g", price: 110 }],
    featured: false,
    shelfLife: "3 months",
    recipe: "Mash two small boiled potatoes and mix in a spoon of crushed peanuts, salt, and crushed green chillies or red chilli powder (to taste) with Bhagwati Upvas Bhajani. Knead well with a little water or buttermilk and let it rest for 5 minutes. Cook on a tawa with ghee on both sides until golden and crisp. This thalipeeth tastes wonderful with butter or curd.",
    recipeMarathi: "दोन लहान आकाराचे बटाटे (उकडून बारीक केलेले) एक चमचा शेंगदाण्याचा कुट, मीठ, वाटलेल्या हिरव्या मिरच्या किंवा लाल तिखट (चवीप्रमाणे) हे सर्व साहित्य भगवती उपवास भाजणीत मिसळून थोडे पाणी किंवा ताक यात चांगले मळून घ्या आणि पाच मिनिटे भिजवून घ्या. तव्यावर सगळीकडून तूप सोडून दोन्ही बाजूने सोनेरी रंगावर खरपूस भाजून घ्या. लोणी किंवा दही यासोबत हे थालीपीठ छान लागते.",
    emoji: "🥞",
    image: "/products/upvas-bhajani-500-new.png",
  },
  {
    id: 8,
    slug: "thalipeeth-bhajani",
    name: "Thalipeeth Bhajani",
    nameMarathi: "थालीपीठ भाजणी",
    category: "flour",
    ingredients: "Jwari, Gahu, Tandul, Chanadal, Mungdal, Jeera, Hing, Ova",
    ingredientsMarathi: "ज्वारी, गहू, तांदूळ, चणादाळ, मूगदाळ, जिरे, हिंग, ओवा",
    usage: "Thalipeeth with curd or chutney",
    usageMarathi: "दही किंवा चटणीसोबत थालीपीठ",
    description: "Seven-grain Maharashtrian classic – just add veggies, mix and cook on a hot tawa.",
    descriptionMarathi: "सात धान्यांची पारंपरिक महाराष्ट्रीयन भाजणी – भाज्या घालून मिसळा आणि गरम तव्यावर भाजा.",
    variants: [{ weight: "200g", price: 45 }],
    featured: true,
    shelfLife: "3 months",
    recipe: "Take finely chopped vegetables, onion, garlic, chilli powder, salt, and turmeric, and mix with water into Bhagwati Thalipeeth Bhajani. Shape into a dough ball and set aside for 5 minutes. Roll a small portion on a plastic sheet. Cook on a tawa with oil until golden and crisp. Enjoy with curd or sauce.",
    recipeMarathi: "सर्व बारीक चिरलेल्या भाज्या, कांदा, लसून, तिखट, मीठ, हळद हे घेऊन भगवती थालीपीठ पिठात पाण्यासोबत मिक्स करा. गोळा करून ५ मिनिटांसाठी बाजूला ठेवा. नंतर प्लास्टिक पेपरवर छोटा गोळा घेऊन लाटा. तव्यावर तेल टाकून खरपूस भाजून घ्या. दही किंवा सॉस सोबत याचा आस्वाद घ्या.",
    emoji: "🫓",
    image: "/products/thalipeeth-bhajani-new.png",
  },
  {
    id: 9,
    slug: "tandul-pithi",
    name: "Tandul Pithi",
    nameMarathi: "तांदूळ पीठी",
    category: "flour",
    ingredients: "Suvasik Tandul (Fragrant Rice)",
    ingredientsMarathi: "सुवासिक तांदूळ",
    usage: "Ukadiche Modak, chapati, dosa, ghavan",
    usageMarathi: "उकडीचे मोदक, चपाती, डोसा, घावन",
    description: "Protein & fibre-rich fragrant rice flour – the essential ingredient for ukadiche modak.",
    descriptionMarathi: "प्रथिने व तंतुमय पदार्थांनी समृद्ध सुवासिक तांदूळ पीठ – उकडीच्या मोदकांसाठी आवश्यक घटक.",
    variants: [{ weight: "200g", price: 52 }],
    featured: false,
    shelfLife: "6 months",
    emoji: "🍚",
    image: "/products/tandul-pithi-new.png",
  },
  {
    id: 10,
    slug: "bajri-pith",
    name: "Bajri Pith",
    nameMarathi: "बाजरी पीठ",
    category: "flour",
    ingredients: "Bajri (Pearl Millet)",
    ingredientsMarathi: "बाजरी",
    usage: "Bhakri, thalipeeth",
    usageMarathi: "भाकरी, थालीपीठ",
    description: "Iron-rich pearl millet flour for traditional warm bhakri.",
    descriptionMarathi: "लोहयुक्त बाजरी पीठ – पारंपरिक गरमागरम भाकरीसाठी.",
    variants: [{ weight: "500g", price: 45 }],
    featured: false,
    shelfLife: "3 months",
    emoji: "🌾",
    image: "/products/bajri-pith-new.png",
  },
  {
    id: 11,
    slug: "jwari-pith",
    name: "Jwari Pith",
    nameMarathi: "ज्वारी पीठ",
    category: "flour",
    ingredients: "Jwari (Sorghum)",
    ingredientsMarathi: "ज्वारी",
    usage: "Bhakri, thalipeeth",
    usageMarathi: "भाकरी, थालीपीठ",
    description: "Classic sorghum flour for soft, nutritious Maharashtrian bhakri.",
    descriptionMarathi: "मऊसूत व पौष्टिक महाराष्ट्रीयन भाकरीसाठी पारंपरिक ज्वारी पीठ.",
    variants: [{ weight: "500g", price: 55 }],
    featured: false,
    shelfLife: "1 month",
    emoji: "🌾",
    image: "/products/jwari-pith-new.png",
  },
  {
    id: 12,
    slug: "dal-batti-ata",
    name: "Dal Batti Ata",
    nameMarathi: "दाळ बट्टी आटा",
    category: "flour",
    ingredients: "Gahu, Harbhara Dal, Maka, Soyabean, Ova, Khata Soda, Halad",
    ingredientsMarathi: "गहू, हरभरा डाळ, मका, सोयाबीन, ओवा, खाण्याचा सोडा, हळद",
    usage: "Dal batti",
    usageMarathi: "दाळ बट्टी",
    description: "Ready-blend for authentic dal batti – just knead, shape and boil.",
    descriptionMarathi: "अस्सल दाळ बट्टीसाठी तयार मिश्रण – मळा, आकार द्या आणि उकळा.",
    variants: [{ weight: "1kg", price: 120 }],
    featured: false,
    shelfLife: "4 months",
    emoji: "🫓",
    image: "/products/dal-batti-ata-new.png",
  },
  {
    id: 13,
    slug: "anarse-pith",
    name: "Anarse Pith",
    nameMarathi: "अनारसे पीठ",
    category: "flour",
    ingredients: "Tandul, Sakhar",
    ingredientsMarathi: "तांदूळ, साखर",
    usage: "Anarse (fried sweet)",
    usageMarathi: "अनारसे (तळणीची मिठाई)",
    description: "Traditional rice-sugar blend for making the beloved Diwali sweet – anarse.",
    descriptionMarathi: "दिवाळीतील लोकप्रिय गोड पदार्थ अनारसे बनवण्यासाठी पारंपरिक तांदूळ-साखर मिश्रण.",
    variants: [{ weight: "1kg", price: 200 }],
    featured: false,
    shelfLife: "1 month",
    emoji: "🍮",
    image: "/products/anarse-pith-new.png",
  },
  {
    id: 14,
    slug: "chakali-bhajani-pith",
    name: "Chakali Bhajani Pith",
    nameMarathi: "चकली भाजणी पीठ",
    category: "flour",
    ingredients: "Tandul, Harbhara Dal, Til, Ova, Halad, Mith, Chana Powder",
    ingredientsMarathi: "तांदूळ, हरभरा डाळ, तीळ, ओवा, हळद, मीठ, चणा पावडर",
    usage: "Chakali (crispy spirals)",
    usageMarathi: "चकली (कुरकुरीत स्पायरल)",
    description: "Pre-mixed chakali bhajani – just knead with water and oil, press and fry.",
    descriptionMarathi: "तयार चकली भाजणी – पाणी व तेल घालून मळा, साच्यात दाबा आणि तळा.",
    variants: [{ weight: "1kg", price: 240 }],
    featured: true,
    shelfLife: "3 months",
    emoji: "🌀",
    image: "/products/chakali-bhajani-pith-new.png",
  },
  {
    id: 15,
    slug: "multigrain-atta",
    name: "Multigrain Atta",
    nameMarathi: "मल्टीग्रेन आटा",
    category: "flour",
    ingredients: "Gahu, Jwari, Bajri, Nachni, Maka, Soyabean, Ova",
    ingredientsMarathi: "गहू, ज्वारी, बाजरी, नाचणी, मका, सोयाबीन, ओवा",
    usage: "Chapati, bhakri, paratha",
    usageMarathi: "चपाती, भाकरी, पराठा",
    description: "Seven-grain wholesome atta for daily rotis – nutritious and high in fibre.",
    descriptionMarathi: "रोजच्या पोळीसाठी सात धान्यांचे पौष्टिक आटा – तंतुमय पदार्थांनी समृद्ध.",
    variants: [{ weight: "1kg", price: 90 }, { weight: "5kg", price: 400 }],
    featured: true,
    isNew: true,
    shelfLife: "3 months",
    emoji: "🌾",
    image: "/products/multigrain-atta-new.png",
  },
  {
    id: 16,
    slug: "nachni-pith",
    name: "Nachni Pith",
    nameMarathi: "नाचणी पीठ",
    category: "flour",
    ingredients: "Nachni (Finger Millet / Ragi)",
    ingredientsMarathi: "नाचणी (रागी)",
    usage: "Bhakri, thalipeeth, porridge",
    usageMarathi: "भाकरी, थालीपीठ, पेज",
    description: "Calcium-rich finger millet flour for wholesome bhakri and healthy porridge.",
    descriptionMarathi: "कॅल्शियमयुक्त नाचणी पीठ – पौष्टिक भाकरी व आरोग्यदायी पेजेसाठी.",
    variants: [{ weight: "500g", price: 50 }],
    featured: false,
    shelfLife: "3 months",
    emoji: "🌾",
    image: "/products/nachni-pith-new.png",
  },
  {
    id: 17,
    slug: "makai-pith",
    name: "Makai Pith",
    nameMarathi: "मका पीठ",
    category: "flour",
    ingredients: "Makai (Corn)",
    ingredientsMarathi: "मका",
    usage: "Bhakri, thalipeeth, porridge",
    usageMarathi: "भाकरी, थालीपीठ, पेज",
    description: "Stone-ground corn flour for golden, crispy makki bhakri.",
    descriptionMarathi: "सोनसळी व कुरकुरीत मक्याच्या भाकरीसाठी दगडावर दळलेले मका पीठ.",
    variants: [{ weight: "500g", price: 45 }],
    featured: false,
    shelfLife: "2 months",
    emoji: "🌽",
    image: "/products/makai-pith-new.png",
  },
  {
    id: 18,
    slug: "singhara-pith",
    name: "Singhara Pith",
    nameMarathi: "सिंघाडा पीठ",
    category: "flour",
    ingredients: "Singhara (Water Chestnut)",
    ingredientsMarathi: "सिंघाडा",
    usage: "Fasting halwa, puri, pakoda",
    usageMarathi: "उपवासाचा हलवा, पुरी, भजी",
    description: "Pure water chestnut flour ideal for fasting – makes soft puris and delicious halwa.",
    descriptionMarathi: "उपवासासाठी उत्तम शुद्ध सिंघाडा पीठ – मऊसूत पुरी व स्वादिष्ट हलवा बनवण्यासाठी.",
    variants: [{ weight: "200g", price: 60 }],
    featured: false,
    shelfLife: "3 months",
    recipe: "Roast Bhagwati Singhara Pith well in half a cup of pure ghee. Add dried-date powder and grated coconut (to taste) and roast a little longer. Then mix in powdered sugar and cardamom powder to taste, and shape into ladoos. You can also make bhajiya, thokala, and shira from Bhagwati Singhara Pith.",
    recipeMarathi: "१/२ कप शुध्द तुपात भगवती शिंगाडा पीठ खमंग भाजून घ्या. भाजलेल्या पिठात खारीक पावडर, नारळाचा कीस (आवडीप्रमाणे) थोडा वेळ भाजून घ्या. नंतर त्यात चवीप्रमाणे पिठी साखर आणि विलायची पावडर टाकून मळून घ्या आणि लाडू बांधून घ्या. भगवती शिंगाडा पिठापासून तुम्ही भजी, ठोकळा आणि शिरा ही बनवू शकता.",
    emoji: "🤍",
    image: "/products/singhara-pith-new.png",
  },
  {
    id: 19,
    slug: "besan",
    name: "Besan",
    nameMarathi: "बेसन",
    category: "flour",
    ingredients: "Chana Dal (Bengal Gram)",
    ingredientsMarathi: "चणा डाळ",
    usage: "Kadhi, bhaji, ladoo, pakoda",
    usageMarathi: "कढी, भाजी, लाडू, भजी",
    description: "Finely milled gram flour for everyday cooking – kadhi, pakoda, besan ladoo and more.",
    descriptionMarathi: "रोजच्या स्वयंपाकासाठी बारीक दळलेले बेसन – कढी, भजी, बेसन लाडू आणि बरेच काही.",
    variants: [{ weight: "500g", price: 60 }, { weight: "1kg", price: 110 }],
    featured: false,
    shelfLife: "6 months",
    emoji: "🟡",
    image: "/products/besan-new.png",
  },

  // ── CHUTNEYS ──────────────────────────────────────────────────────────────
  {
    id: 20,
    slug: "shengdana-chatni",
    name: "Shengdana Chatni",
    nameMarathi: "शेंगदाना चटणी",
    category: "chatni",
    ingredients: "Shengdana, Mith, Tikhat, Lasun",
    ingredientsMarathi: "शेंगदाणा, मीठ, तिखट, लसूण",
    usage: "Side dish with any meal, bhakri",
    usageMarathi: "जेवणासोबत किंवा भाकरीसोबत",
    description: "Spicy roasted peanut chutney with garlic – a Maharashtrian table staple.",
    descriptionMarathi: "लसणासह तिखट भाजलेल्या शेंगदाण्याची चटणी – महाराष्ट्रीयन जेवणातील आवश्यक पदार्थ.",
    variants: [{ weight: "100g", price: 30 }],
    featured: true,
    shelfLife: "6 months",
    emoji: "🥜",
    image: "/products/shengdana-chatni-new.png",
  },
  {
    id: 21,
    slug: "shengdana-upvas-chatni",
    name: "Shengdana Upvas Chatni",
    nameMarathi: "शेंगदाना उपवास चटणी",
    category: "chatni",
    ingredients: "Shengdana, Mith, Tikhat",
    ingredientsMarathi: "शेंगदाणा, मीठ, तिखट",
    usage: "Fasting meals, sabudana khichdi",
    usageMarathi: "उपवासाचे जेवण, साबुदाणा खिचडी",
    description: "Peanut chutney without garlic – perfect for fasting days with sabudana khichdi.",
    descriptionMarathi: "लसणाशिवाय शेंगदाण्याची चटणी – उपवासाच्या दिवशी साबुदाणा खिचडीसोबत उत्तम.",
    variants: [{ weight: "100g", price: 30 }],
    featured: false,
    shelfLife: "6 months",
    emoji: "🥜",
    image: "/products/shengdana-upvas-chatni-new.png",
  },
  {
    id: 22,
    slug: "til-chatni",
    name: "Til Chatni",
    nameMarathi: "तीळ चटणी",
    category: "chatni",
    ingredients: "Til, Mith, Tikhat, Lasun",
    ingredientsMarathi: "तीळ, मीठ, तिखट, लसूण",
    usage: "Side dish, bhakri accompaniment",
    usageMarathi: "जेवणासोबत, भाकरीसोबत",
    description: "Nutty sesame chutney with a punch of garlic and spice.",
    descriptionMarathi: "लसूण व तिखटाचा खमंग स्वाद असलेली तिळाची चटणी.",
    variants: [{ weight: "100g", price: 35 }],
    featured: true,
    shelfLife: "2 months",
    emoji: "🫙",
    image: "/products/til-chatni-new.png",
  },
  {
    id: 23,
    slug: "javas-chatni",
    name: "Javas Chatni",
    nameMarathi: "जवस चटणी",
    category: "chatni",
    ingredients: "Javas (Flaxseed), Mith, Tikhat, Lasun",
    ingredientsMarathi: "जवस, मीठ, तिखट, लसूण",
    usage: "Side dish, spread on bhakri",
    usageMarathi: "जेवणासोबत, भाकरीवर लावण्यासाठी",
    description: "Omega-rich flaxseed chutney – healthy, spicy and flavourful.",
    descriptionMarathi: "ओमेगायुक्त जवसाची चटणी – आरोग्यदायी, तिखट व चविष्ट.",
    variants: [{ weight: "100g", price: 35 }],
    featured: false,
    shelfLife: "2 months",
    emoji: "🌿",
    image: "/products/javas-chatni-new.png",
  },
  {
    id: 24,
    slug: "karal-chatni",
    name: "Karal Chatni",
    nameMarathi: "कारळ चटणी",
    category: "chatni",
    ingredients: "Karal (Niger Seeds), Mith, Tikhat, Lasun",
    ingredientsMarathi: "कारळे, मीठ, तिखट, लसूण",
    usage: "Side dish, bhakri",
    usageMarathi: "जेवणासोबत, भाकरीसोबत",
    description: "Traditional niger seed chutney – earthy, aromatic and packed with nutrients.",
    descriptionMarathi: "पौष्टिक व खमंग पारंपरिक कारळ्याची चटणी.",
    variants: [{ weight: "100g", price: 35 }],
    featured: false,
    shelfLife: "6 months",
    emoji: "🫙",
    image: "/products/karal-chatni-new.png",
  },
  // ── MUKHWAS ───────────────────────────────────────────────────────────────
  {
    id: 29,
    slug: "mukhwas-sauf-til-dhanadal",
    name: "Mukhwas (Sauf, Til, Dhanadal)",
    nameMarathi: "मुखवास (सौंफ, तीळ, धनादाळ)",
    category: "mukhwas",
    ingredients: "Saunf, Til, Dhanadal",
    ingredientsMarathi: "सौंफ, तीळ, धनादाळ",
    usage: "After-meal mouth freshener",
    usageMarathi: "जेवणानंतर मुखशुद्धीसाठी",
    description: "Classic three-seed mukhwas – fennel, sesame and roasted coriander dal.",
    descriptionMarathi: "सौंफ, तीळ व भाजलेली धनादाळ यांचे पारंपरिक तीन-बियांचे मुखवास.",
    variants: [{ weight: "100g", price: 40 }],
    featured: true,
    shelfLife: "6 months",
    emoji: "🌿",
    image: "/products/mukhwas-sauf-til-dhanadal-new.png",
  },
  {
    id: 30,
    slug: "mukhwas-sauf-til",
    name: "Mukhwas (Sauf & Til)",
    nameMarathi: "मुखवास (सौंफ आणि तीळ)",
    category: "mukhwas",
    ingredients: "Saunf, Til, Mith",
    ingredientsMarathi: "सौंफ, तीळ, मीठ",
    usage: "After-meal mouth freshener",
    usageMarathi: "जेवणानंतर मुखशुद्धीसाठी",
    description: "Simple two-seed blend of fennel and sesame – light and refreshing.",
    descriptionMarathi: "सौंफ व तिळाचे साधे मिश्रण – हलके व ताजेतवाने.",
    variants: [{ weight: "100g", price: 40 }],
    featured: false,
    shelfLife: "6 months",
    emoji: "🌿",
    image: "/products/mukhwas-sauf-til-new2.png",
  },
  {
    id: 31,
    slug: "mukhwas-sauf-til-ova",
    name: "Mukhwas (Sauf, Til, Ova)",
    nameMarathi: "मुखवास (सौंफ, तीळ, ओवा)",
    category: "mukhwas",
    ingredients: "Saunf, Til, Ova (Carom seeds)",
    ingredientsMarathi: "सौंफ, तीळ, ओवा",
    usage: "After-meal mouth freshener & digestive",
    usageMarathi: "जेवणानंतर मुखशुद्धी व पचनासाठी",
    description: "Digestive mukhwas with carom seeds – great after heavy meals.",
    descriptionMarathi: "ओव्यासह पचनास उपयुक्त मुखवास – जड जेवणानंतर उत्तम.",
    variants: [{ weight: "100g", price: 40 }],
    featured: false,
    shelfLife: "6 months",
    emoji: "🌿",
    image: "/products/mukhwas-sauf-til-ova-new.png",
  },
  {
    id: 32,
    slug: "meetha-mukhwas",
    name: "Meetha Mukhwas",
    nameMarathi: "मीठा मुखवास",
    category: "mukhwas",
    ingredients: "Dhanadal, Saunf, Khadi Sakhar",
    ingredientsMarathi: "धनादाळ, सौंफ, खडी साखर",
    usage: "Sweet after-meal refresher",
    usageMarathi: "जेवणानंतर गोड मुखशुद्धी",
    description: "Colourful sweet mukhwas with rock sugar coated seeds – a favourite for all ages.",
    descriptionMarathi: "खडी साखरेचा थर असलेले रंगीबेरंगी गोड मुखवास – सर्व वयोगटांना आवडणारे.",
    variants: [{ weight: "100g", price: 40 }],
    featured: true,
    shelfLife: "6 months",
    emoji: "🍬",
    image: "/products/meetha-mukhwas-new.png",
  },
  {
    id: 33,
    slug: "mukhwas-javas",
    name: "Mukhwas (Javas)",
    nameMarathi: "मुखवास (जवस)",
    category: "mukhwas",
    ingredients: "Javas (Flaxseed), Mith",
    ingredientsMarathi: "जवस, मीठ",
    usage: "After-meal refresher & digestive",
    usageMarathi: "जेवणानंतर मुखशुद्धी व पचनासाठी",
    description: "Pure flaxseed mukhwas – nutritious and naturally digestive.",
    descriptionMarathi: "शुद्ध जवसाचे मुखवास – पौष्टिक व नैसर्गिकरित्या पचनास उपयुक्त.",
    variants: [{ weight: "100g", price: 40 }],
    featured: false,
    shelfLife: "6 months",
    emoji: "🌿",
    image: "/products/mukhwas-javas-new.png",
  },
  // ── SWEETS ────────────────────────────────────────────────────────────────
  {
    id: 38,
    slug: "balu-shahi",
    name: "Balu Shahi",
    nameMarathi: "बालू शाही",
    category: "sweets",
    ingredients: "Maida, Sakhar, Tup, Baking Powder",
    ingredientsMarathi: "मैदा, साखर, तूप, बेकिंग पावडर",
    usage: "Festive sweet, gift",
    usageMarathi: "सणासुदीची मिठाई, भेट",
    description: "Flaky, melt-in-mouth fried sweet soaked in sugar syrup – a festive delight.",
    descriptionMarathi: "साखरेच्या पाकात भिजवलेली खुसखुशीत व तोंडात विरघळणारी तळणीची मिठाई – सणासुदीचा आनंद.",
    variants: [{ weight: "500g", price: 70 }],
    featured: true,
    shelfLife: "1 month",
    emoji: "🍮",
    image: "/products/balu-shahi-new.png",
  },
  {
    id: 39,
    slug: "besan-ladoo",
    name: "Besan Ladoo",
    nameMarathi: "बेसन लाडू",
    category: "sweets",
    ingredients: "Chana Dal, Sajuk Tup, Sakhar, Dryfruit",
    ingredientsMarathi: "चणादाळ, साजूक तूप, साखर, सुकामेवा",
    usage: "Festive sweet, prasad, gift",
    usageMarathi: "सणासुदीची मिठाई, प्रसाद, भेट",
    description: "Slow-roasted gram flour ladoo with pure ghee and dry fruits.",
    descriptionMarathi: "साजूक तूप व सुकामेव्यासह मंद आचेवर भाजलेले बेसन लाडू.",
    variants: [{ weight: "500g", price: 250 }, { weight: "1kg", price: 480 }],
    featured: true,
    shelfLife: "2 months",
    emoji: "🍡",
    image: "/products/besan-ladoo-new.png",
  },
  {
    id: 40,
    slug: "karanji",
    name: "Karanji",
    nameMarathi: "करंजी",
    category: "sweets",
    ingredients: "Rava, Khobre, Sakhar, Khaskhas, Vanaspati Tee",
    ingredientsMarathi: "रवा, खोबरे, साखर, खसखस, वनस्पती तूप",
    usage: "Diwali sweet, gift pack",
    usageMarathi: "दिवाळीची मिठाई, भेट पॅक",
    description: "Crispy half-moon pastry filled with sweet coconut and poppy seed stuffing.",
    descriptionMarathi: "गोड खोबरे व खसखशीच्या सारणाने भरलेली कुरकुरीत अर्धचंद्राकृती करंजी.",
    variants: [{ weight: "500g", price: 220 }],
    featured: true,
    shelfLife: "1 month",
    emoji: "🥮",
    image: "/products/karanji-new.png",
  },
  {
    id: 41,
    slug: "shankarpale",
    name: "Shankarpale",
    nameMarathi: "शंकरपाळे",
    category: "sweets",
    ingredients: "Maida, Sakhar, Tup, Tel / Shuddh Tup",
    ingredientsMarathi: "मैदा, साखर, तूप, तेल / शुद्ध तूप",
    usage: "Tea-time snack, Diwali sweet",
    usageMarathi: "चहासोबतचा नाश्ता, दिवाळीची मिठाई",
    description: "Diamond-shaped fried pastry squares – buttery, mildly sweet and perfectly crisp.",
    descriptionMarathi: "हिऱ्याच्या आकाराचे तळणीचे तुकडे – खुसखुशीत व सौम्य गोड.",
    variants: [{ weight: "500g", price: 170 }],
    featured: false,
    shelfLife: "1 month",
    emoji: "🍪",
    image: "/products/shankarpale-new.png",
  },
  {
    id: 42,
    slug: "rava-ladoo",
    name: "Rava Ladoo",
    nameMarathi: "रवा लाडू",
    category: "sweets",
    ingredients: "Rava (Semolina), Sakhar, Tup, Elaichi, Dry Fruits",
    ingredientsMarathi: "रवा, साखर, तूप, वेलची, सुकामेवा",
    usage: "Festive sweet, prasad, gift",
    usageMarathi: "सणासुदीची मिठाई, प्रसाद, भेट",
    description: "Light, crumbly semolina ladoo with ghee and cardamom – melt-in-the-mouth sweetness.",
    descriptionMarathi: "तूप व वेलचीसह हलके व खुसखुशीत रवा लाडू – तोंडात विरघळणारा गोडवा.",
    variants: [{ weight: "500g", price: 200 }, { weight: "1kg", price: 380 }],
    featured: false,
    shelfLife: "1 month",
    emoji: "🍡",
    image: "/products/rava-ladoo-new.png",
  },
  {
    id: 45,
    slug: "shengdana-chikki",
    name: "Shengdana Chikki",
    nameMarathi: "शेंगदाणा चिक्की",
    category: "sweets",
    ingredients: "Shengdana (Peanuts), Gul (Jaggery)",
    ingredientsMarathi: "शेंगदाणे, गूळ",
    usage: "Snack, Makar Sankranti special, gift",
    usageMarathi: "नाश्ता, मकर संक्रांती विशेष, भेट",
    description: "Crispy peanut brittle with jaggery – energy-packed and traditionally made.",
    descriptionMarathi: "गुळासह कुरकुरीत शेंगदाणा चिक्की – ऊर्जादायी व पारंपरिक पद्धतीने बनवलेली.",
    variants: [{ weight: "250g", price: 80 }, { weight: "500g", price: 150 }],
    featured: true,
    shelfLife: "2 months",
    emoji: "🟤",
    image: "/products/shengdana-chikki-new.png",
  },
  {
    id: 46,
    slug: "tilgul",
    name: "Tilgul",
    nameMarathi: "तिळगूळ",
    category: "sweets",
    ingredients: "Til (Sesame), Gul (Jaggery)",
    ingredientsMarathi: "तीळ, गूळ",
    usage: "Makar Sankranti, prasad, gift",
    usageMarathi: "मकर संक्रांती, प्रसाद, भेट",
    description: "The iconic Sankranti sweet – sesame and jaggery balls with a warming sweetness.",
    descriptionMarathi: "संक्रांतीची खास मिठाई – तीळ व गुळाचे लाडू, उबदार गोडवा.",
    variants: [{ weight: "250g", price: 80 }],
    featured: false,
    shelfLife: "2 months",
    emoji: "⚫",
    image: "/products/til-ladoo-new.png",
  },

  // ── SNACKS ────────────────────────────────────────────────────────────────
  {
    id: 47,
    slug: "bhadang",
    name: "Bhadang",
    nameMarathi: "भडंग",
    category: "snacks",
    ingredients: "Murmure, Shengdane, Tikhat, Lasun, Khaadyatel",
    ingredientsMarathi: "मुरमुरे, शेंगदाणे, तिखट, लसूण, खाद्यतेल",
    usage: "Snack, timepass",
    usageMarathi: "नाश्ता, टाईमपास",
    description: "Spicy puffed rice with peanuts – Aurangabad's famous crunchy snack.",
    descriptionMarathi: "शेंगदाण्यांसह तिखट मुरमुरे – औरंगाबादचा प्रसिद्ध कुरकुरीत नाश्ता.",
    variants: [{ weight: "200g", price: 60 }],
    featured: true,
    shelfLife: "2 months",
    emoji: "🍿",
    image: "/products/bhadang-front.jpg",
  },
  {
    id: 48,
    slug: "paani-puri",
    name: "Paani Puri",
    nameMarathi: "पाणी पुरी",
    category: "snacks",
    ingredients: "Wheat, Semolina",
    ingredientsMarathi: "गहू, रवा",
    usage: "Street-food style pani puri at home",
    usageMarathi: "घरीच रस्त्यावरील स्टॉलसारखी पाणीपुरी",
    description: "Ready-to-fry crispy puri shells – just fry and fill for perfect pani puri.",
    descriptionMarathi: "तळण्यासाठी तयार कुरकुरीत पुरी – फक्त तळा आणि भरा, उत्तम पाणीपुरी तयार.",
    variants: [
      { weight: "240g / 100 pcs", price: 45 },
      { weight: "120g / 50 pcs", price: 25 },
    ],
    featured: false,
    shelfLife: "3 months",
    emoji: "🫧",
    image: "/products/paani-puri-front.jpg",
  },
  {
    id: 49,
    slug: "chivda",
    name: "Poha Chivda",
    nameMarathi: "पोहा चिवडा",
    category: "snacks",
    ingredients: "Poha (Flattened Rice), Shengdane, Curry Patta, Tikhat, Halad",
    ingredientsMarathi: "पोहे, शेंगदाणे, कढीपत्ता, तिखट, हळद",
    usage: "Snack, tea-time, Diwali faral",
    usageMarathi: "नाश्ता, चहासोबत, दिवाळी फराळ",
    description: "Light and crispy flattened rice snack with peanuts and curry leaves – Diwali must-have.",
    descriptionMarathi: "शेंगदाणे व कढीपत्त्यासह हलका व कुरकुरीत पोहा चिवडा – दिवाळी फराळातील आवश्यक पदार्थ.",
    variants: [{ weight: "200g", price: 60 }, { weight: "500g", price: 130 }],
    featured: true,
    shelfLife: "2 months",
    emoji: "🥣",
    image: "/products/pohe-chivda.png",
  },
  {
    id: 50,
    slug: "masala-shengdana",
    name: "Masala Shengdana",
    nameMarathi: "मसाला शेंगदाणे",
    category: "snacks",
    ingredients: "Shengdana, Besan, Tikhat, Halad, Mith, Hing",
    ingredientsMarathi: "शेंगदाणे, बेसन, तिखट, हळद, मीठ, हिंग",
    usage: "Snack, timepass",
    usageMarathi: "नाश्ता, टाईमपास",
    description: "Crunchy spice-coated roasted peanuts – the perfect anytime snack.",
    descriptionMarathi: "मसाल्याचा लेप असलेले कुरकुरीत भाजलेले शेंगदाणे – कधीही खाण्यासाठी उत्तम नाश्ता.",
    variants: [{ weight: "200g", price: 50 }],
    featured: false,
    shelfLife: "3 months",
    emoji: "🥜",
    image: "/products/masala-shengdana-new.png",
  },
  {
    id: 51,
    slug: "shev",
    name: "Rassa Shev",
    nameMarathi: "रस्सा शेव",
    category: "snacks",
    ingredients: "Besan, Tikhat, Halad, Hing, Tel",
    ingredientsMarathi: "बेसन, तिखट, हळद, हिंग, तेल",
    usage: "Bhel, chaat, snack",
    usageMarathi: "भेळ, चाट, नाश्ता",
    description: "Fine, crispy gram flour noodles – perfect for bhel puri and chaat toppings.",
    descriptionMarathi: "बारीक व कुरकुरीत बेसन शेव – भेळपुरी व चाटसाठी उत्तम.",
    variants: [{ weight: "200g", price: 45 }],
    featured: false,
    shelfLife: "2 months",
    emoji: "🍜",
    image: "/products/shev-new.png",
  },
  {
    id: 53,
    slug: "papdi",
    name: "Papdi",
    nameMarathi: "पापडी",
    category: "snacks",
    ingredients: "Maida, Tel, Ajwain, Mith",
    ingredientsMarathi: "मैदा, तेल, ओवा, मीठ",
    usage: "Chaat, snack",
    usageMarathi: "चाट, नाश्ता",
    description: "Crispy flat crackers for chaat, dahi papdi and sev puri.",
    descriptionMarathi: "चाट, दही पापडी व शेवपुरीसाठी कुरकुरीत पापडी.",
    variants: [{ weight: "200g", price: 40 }],
    featured: false,
    shelfLife: "3 months",
    emoji: "🫓",
    image: "/products/papadi-new.png",
  },

  // ── MASALAS ───────────────────────────────────────────────────────────────
  {
    id: 54,
    slug: "kala-masala",
    name: "Kala Masala",
    nameMarathi: "काळा मसाला",
    category: "masala",
    ingredients: "Various whole spices",
    ingredientsMarathi: "विविध संपूर्ण मसाले",
    usage: "Curries, bhaji, dal",
    usageMarathi: "भाजी, आमटी, वरण",
    description: "The signature Maharashtrian black spice blend – deep, smoky and aromatic.",
    descriptionMarathi: "महाराष्ट्राचा खास काळा मसाला – गहिरा, धुरकट व सुगंधी.",
    variants: [{ weight: "100g", price: 60 }],
    featured: true,
    shelfLife: "6 months",
    emoji: "🫙",
    image: "/products/kala-masala-new.png",
  },
  {
    id: 63,
    slug: "chaat-masala",
    name: "Chaat Masala",
    nameMarathi: "चाट मसाला",
    category: "masala",
    ingredients: "Amchur, Kala Namak, Jeera, Dhania, Pudina, Hing",
    ingredientsMarathi: "आमचूर, काळे मीठ, जिरे, धणे, पुदिना, हिंग",
    usage: "Chaat, pani puri, salads, snacks",
    usageMarathi: "चाट, पाणीपुरी, सॅलड, नाश्ता",
    description: "Zesty chaat masala that adds instant street-food flavour to any snack.",
    descriptionMarathi: "कोणत्याही नाश्त्याला रस्त्यावरील चवीचा तडका देणारा चटपटीत चाट मसाला.",
    variants: [{ weight: "100g", price: 35 }],
    featured: false,
    shelfLife: "12 months",
    emoji: "🫙",
    image: "/products/chaat-masala-new.png",
  },

  // ── NEW SNACKS ────────────────────────────────────────────────────────────
  {
    id: 64,
    slug: "chakali",
    name: "Chakali",
    nameMarathi: "चकली",
    category: "snacks",
    ingredients: "Tandul Pith, Harbhara Dal, Til, Ova, Halad, Mith",
    ingredientsMarathi: "तांदूळ पीठ, हरभरा डाळ, तीळ, ओवा, हळद, मीठ",
    usage: "Snack, Diwali faral, tea-time",
    usageMarathi: "नाश्ता, दिवाळी फराळ, चहासोबत",
    description: "Crispy deep-fried rice flour spirals – the iconic Maharashtrian Diwali snack.",
    descriptionMarathi: "कुरकुरीत तळलेल्या तांदूळ पिठाच्या स्पायरल – महाराष्ट्रीयन दिवाळीचा खास पदार्थ.",
    variants: [{ weight: "200g", price: 80 }, { weight: "500g", price: 180 }],
    featured: true,
    shelfLife: "2 months",
    emoji: "🌀",
    image: "/products/chakali-new.png",
  },
  {
    id: 65,
    slug: "potato-chips",
    name: "Potato Chips",
    nameMarathi: "बटाटा चिप्स",
    category: "snacks",
    ingredients: "Potato, Salt, Spices, Oil",
    ingredientsMarathi: "बटाटा, मीठ, मसाले, तेल",
    usage: "Snack, tea-time, tiffin",
    usageMarathi: "नाश्ता, चहासोबत, डबा",
    description: "Thin crispy potato slices fried to golden perfection – lightly salted and spiced.",
    descriptionMarathi: "सोनसळी रंगापर्यंत तळलेले पातळ व कुरकुरीत बटाटा चिप्स – हलके खारट व मसालेदार.",
    variants: [{ weight: "100g", price: 40 }, { weight: "200g", price: 70 }],
    featured: false,
    shelfLife: "1 month",
    emoji: "🥔",
    image: "/products/potato-chips-new.png",
  },
  {
    id: 66,
    slug: "banana-chips",
    name: "Banana Chips",
    nameMarathi: "केळी चिप्स",
    category: "snacks",
    ingredients: "Raw Banana, Oil, Salt, Spices",
    ingredientsMarathi: "कच्ची केळी, तेल, मीठ, मसाले",
    usage: "Snack, tea-time, tiffin",
    usageMarathi: "नाश्ता, चहासोबत, डबा",
    description: "Golden crispy raw banana chips – crunchy, mildly spiced and irresistible.",
    descriptionMarathi: "सोनसळी व कुरकुरीत कच्च्या केळीचे चिप्स – चविष्ट व इरेसिस्टिबल.",
    variants: [{ weight: "100g", price: 35 }, { weight: "200g", price: 65 }],
    featured: false,
    shelfLife: "1 month",
    emoji: "🍌",
    image: "/products/banana-chips-new.png",
  },

  // ── NEW ADDITIONS ─────────────────────────────────────────────────────────
  {
    id: 67,
    slug: "pud-chatni",
    name: "Pud Chatni",
    nameMarathi: "पुड चटणी",
    category: "chatni",
    ingredients: "Chana Dal, Udid Dal, White Sesame, Dry Coconut, Dry Red Chilli, Garlic, Jeera, Curry Leaves, Hing, Halad, Mith",
    ingredientsMarathi: "चणा डाळ, उडीद डाळ, पांढरे तीळ, सुके खोबरे, सुकी लाल मिरची, लसूण, जिरे, कढीपत्ता, हिंग, हळद, मीठ",
    usage: "Side dish with bhakri, rice or chapati",
    usageMarathi: "भाकरी, भात किंवा चपातीसोबत",
    description: "A powdered multi-ingredient chutney packed with roasted dals, coconut and spices – a flavourful everyday accompaniment.",
    descriptionMarathi: "भाजलेल्या डाळी, खोबरे व मसाल्यांनी बनलेली पुड चटणी – रोजच्या जेवणासाठी चविष्ट साथ.",
    variants: [{ weight: "100g", price: 35 }],
    featured: false,
    shelfLife: "3 months",
    emoji: "🫙",
    image: "/products/pud-chatni-new.png",
  },
  {
    id: 68,
    slug: "supari",
    name: "Sugandhi Supari",
    nameMarathi: "सुगंधी सुपारी",
    category: "mukhwas",
    ingredients: "Saunf, Mith, Lavang, Velchi, Jaiphal",
    ingredientsMarathi: "सौंफ, मीठ, लवंग, वेलची, जायफळ",
    usage: "After-meal mouth freshener",
    usageMarathi: "जेवणानंतर मुखशुद्धीसाठी",
    description: "Aromatic supari blend with fennel, clove, cardamom and nutmeg – a fragrant after-meal refresher.",
    descriptionMarathi: "सौंफ, लवंग, वेलची व जायफळयुक्त सुगंधी सुपारी – जेवणानंतर ताजेतवाने वाटण्यासाठी.",
    variants: [{ weight: "100g", price: 50 }],
    featured: false,
    shelfLife: "6 months",
    emoji: "🌿",
    image: "/products/supari-new.png",
  },
];

export const testimonials = [
  {
    name: "Priya Kulkarni",
    location: "Aurangabad",
    rating: 5,
    text: "Bhagwati's thalipeeth bhajani tastes exactly like what my aaji used to make. The quality and freshness is unmatched!",
    textMarathi: "भगवतीची थालीपीठ भाजणी माझ्या आजीच्या हातच्या चवीसारखीच लागते. गुणवत्ता आणि ताजेपणा अप्रतिम आहे!",
    product: "Thalipeeth Bhajani",
    productMarathi: "थालीपीठ भाजणी",
  },
  {
    name: "Rahul Deshmukh",
    location: "Pune",
    rating: 5,
    text: "I order bhadang and shengdana chatni every month. The taste is authentic and reminds me of home. Fast delivery too!",
    textMarathi: "मी दरमहा भडंग आणि शेंगदाणा चटणी ऑर्डर करतो. चव अगदी घरच्यासारखी आहे. डिलिव्हरीही जलद!",
    product: "Bhadang & Shengdana Chatni",
    productMarathi: "भडंग आणि शेंगदाणा चटणी",
  },
  {
    name: "Sunita Pawar",
    location: "Mumbai",
    rating: 5,
    text: "The chakali bhajani is fantastic – perfectly spiced and the chakalis come out crispy every single time.",
    textMarathi: "चकली भाजणी खूप छान आहे – मसाला अगदी परफेक्ट आणि चकल्या नेहमी कुरकुरीत होतात.",
    product: "Chakali Bhajani Pith",
    productMarathi: "चकली भाजणी पीठ",
  },
  {
    name: "Amit Shinde",
    location: "Nashik",
    rating: 5,
    text: "Bhagwati's upvas bhajani is the best I've found. My whole family loves the thalipeeth made from it during Navratri.",
    textMarathi: "भगवतीची उपवास भाजणी सर्वोत्तम आहे. नवरात्रीत यापासून बनवलेले थालीपीठ माझ्या संपूर्ण कुटुंबाला खूप आवडते.",
    product: "Upvas Bhajani",
    productMarathi: "उपवास भाजणी",
  },
  {
    name: "Meena Joshi",
    location: "Aurangabad",
    rating: 5,
    text: "The mukhwas varieties are excellent – I always gift them to guests. Premium quality and beautiful packaging.",
    textMarathi: "मुखवासचे प्रकार उत्कृष्ट आहेत – मी नेहमी पाहुण्यांना भेट म्हणून देते. उत्तम दर्जा आणि सुंदर पॅकिंग.",
    product: "Meetha Mukhwas",
    productMarathi: "मीठा मुखवास",
  },
  {
    name: "Suresh Patil",
    location: "Solapur",
    rating: 5,
    text: "Kala masala is something else! Just half a teaspoon transforms the entire curry. Been using Bhagwati for 5 years.",
    textMarathi: "काळा मसाला काही वेगळंच आहे! फक्त अर्धा चमचा संपूर्ण भाजीची चव बदलतो. ५ वर्षांपासून भगवती वापरतोय.",
    product: "Kala Masala",
    productMarathi: "काळा मसाला",
  },
  {
    name: "Mr. Jare",
    location: "Aurangabad",
    rating: 5,
    text: "Bhagwati's Dal Batti Atta Ready Mix is simply outstanding! Restaurant-quality dal batti at home with zero effort. The spice blend is perfect — authentic Rajasthani taste without any hassle. My family loves it!",
    textMarathi: "भगवतीचा दाळ बट्टी आटा रेडी मिक्स खरंच अप्रतिम आहे! घरी कोणत्याही कष्टाशिवाय हॉटेलसारखी दाळ बट्टी बनते. मसाला अगदी परफेक्ट — कोणत्याही त्रासाशिवाय अस्सल राजस्थानी चव. माझ्या कुटुंबाला खूप आवडते!",
    product: "Dal Batti Atta Ready Mix",
    productMarathi: "दाळ बट्टी आटा रेडी मिक्स",
  },
];

export const stats = [
  { value: "18+", label: "Years of Excellence" },
  { value: "50+", label: "Products Available" },
  { value: "10k+", label: "Happy Customers" },
  { value: "100%", label: "Natural Ingredients" },
];

export const faqs = [
  {
    id: 1,
    category: "products",
    question: "What are Bhagwati's most popular products?",
    answer:
      "Our best-sellers are Thalipeeth Bhajani, Shengdana Chatni, Bhadang, Chakali Bhajani Pith, and Upvas Bhajani. All are made with natural ingredients and no preservatives.",
    questionMarathi: "भगवतीची सर्वाधिक लोकप्रिय उत्पादने कोणती आहेत?",
    answerMarathi:
      "आमची सर्वाधिक खरेदी होणारी उत्पादने आहेत थालीपीठ भाजणी, शेंगदाणा चटणी, भडंग, चकली भाजणी पीठ आणि उपवास भाजणी. सर्व नैसर्गिक घटकांपासून आणि कोणत्याही प्रिझर्व्हेटिव्हशिवाय बनवली जातात.",
  },
  {
    id: 2,
    category: "products",
    question: "Are your products suitable for fasting (upvas)?",
    answer:
      "Yes! We have a dedicated fasting range: Upvas Bhajani, Bhagar Pith, Rajgira Pith, Shabudana Pith, Singhara Pith, and Shengdana Upvas Chatni – all free from garlic and onion.",
    questionMarathi: "तुमची उत्पादने उपवासासाठी योग्य आहेत का?",
    answerMarathi:
      "हो! आमच्याकडे खास उपवासाची श्रेणी आहे: उपवास भाजणी, भगर पीठ, राजगिरा पीठ, साबुदाणा पीठ, शिंगाडा पीठ आणि शेंगदाणा उपवास चटणी – सर्व लसूण आणि कांद्याशिवाय.",
  },
  {
    id: 3,
    category: "products",
    question: "Do your products contain preservatives or artificial colours?",
    answer:
      "No. All Bhagwati products are made from pure, natural ingredients without any artificial preservatives, colours or additives. We follow strict hygiene standards throughout manufacturing.",
    questionMarathi: "तुमच्या उत्पादनांमध्ये प्रिझर्व्हेटिव्ह किंवा कृत्रिम रंग असतात का?",
    answerMarathi:
      "नाही. सर्व भगवती उत्पादने शुद्ध, नैसर्गिक घटकांपासून बनवली जातात — कोणतेही कृत्रिम प्रिझर्व्हेटिव्ह, रंग किंवा अॅडिटिव्ह न वापरता. उत्पादन प्रक्रियेत आम्ही कडक स्वच्छता मानके पाळतो.",
  },
  {
    id: 4,
    category: "products",
    question: "What is the shelf life of your products?",
    answer:
      "Shelf life varies by product – flours are typically 3–6 months, chutneys 2–6 months, mukhwas 6 months, sweets 1–2 months, and masalas 6–12 months. Check the label for exact best-before dates.",
    questionMarathi: "तुमच्या उत्पादनांचा टिकाऊपणा किती असतो?",
    answerMarathi:
      "टिकाऊपणा उत्पादनानुसार बदलतो – पीठ साधारण ३–६ महिने, चटणी २–६ महिने, मुखवास ६ महिने, गोड पदार्थ १–२ महिने आणि मसाले ६–१२ महिने टिकतात. नक्की एक्सपायरी तारखेसाठी लेबल तपासा.",
  },
  {
    id: 5,
    category: "ordering",
    question: "How can I place an order?",
    answer:
      "You can order by calling or WhatsApp on +91 9307240577, or fill out our Contact form on the website. We deliver within Aurangabad and can arrange shipping across Maharashtra.",
    questionMarathi: "मी ऑर्डर कशी करू शकतो/शकते?",
    answerMarathi:
      "तुम्ही +91 9307240577 वर कॉल किंवा व्हॉट्सअॅप करून किंवा वेबसाइटवरील कॉन्टॅक्ट फॉर्म भरून ऑर्डर करू शकता. आम्ही औरंगाबादमध्ये डिलिव्हरी करतो आणि महाराष्ट्रभर शिपिंगची व्यवस्था करू शकतो.",
  },
  {
    id: 6,
    category: "ordering",
    question: "Do you offer bulk or wholesale orders?",
    answer:
      "Yes! We offer wholesale pricing for bulk orders. Please contact us on +91 9307240577 or use the contact form to discuss quantities and pricing.",
    questionMarathi: "तुम्ही मोठ्या प्रमाणात (होलसेल) ऑर्डर घेता का?",
    answerMarathi:
      "हो! मोठ्या ऑर्डरसाठी आम्ही होलसेल दर देतो. कृपया +91 9307240577 वर संपर्क करा किंवा प्रमाण आणि दराबाबत चर्चा करण्यासाठी कॉन्टॅक्ट फॉर्म वापरा.",
  },
  {
    id: 7,
    category: "ordering",
    question: "Do you have gift packs available?",
    answer:
      "Yes, we have special gift packs including Karanji, Balu Shahi, Premium Mukhwas, and curated product hampers – perfect for Diwali, weddings and corporate gifting.",
    questionMarathi: "गिफ्ट पॅक उपलब्ध आहेत का?",
    answerMarathi:
      "हो, आमच्याकडे करंजी, बालुशाही, प्रीमियम मुखवास आणि खास निवडलेल्या उत्पादनांचे हॅम्पर्स असलेले खास गिफ्ट पॅक आहेत – दिवाळी, लग्न आणि कॉर्पोरेट गिफ्टिंगसाठी योग्य.",
  },
  {
    id: 8,
    category: "business",
    question: "Where are you located?",
    answer:
      "We are located at Gat No. 88, Satara Parisar, Aurangabad, Maharashtra. You can also reach us on +91 9307240577.",
    questionMarathi: "तुम्ही कुठे आहात?",
    answerMarathi:
      "आम्ही गट नं. ८८, सातारा परिसर, औरंगाबाद, महाराष्ट्र येथे आहोत. तुम्ही +91 9307240577 वरही आमच्याशी संपर्क करू शकता.",
  },
  {
    id: 9,
    category: "business",
    question: "Since when is Bhagwati Industry in operation?",
    answer:
      "Bhagwati Industry and Marketing was established in 2008, starting with Kala Masala and Bhadang. We have successfully completed 18+ years and continue to expand our product range.",
    questionMarathi: "भगवती इंडस्ट्री कधीपासून कार्यरत आहे?",
    answerMarathi:
      "भगवती इंडस्ट्री अँड मार्केटिंगची स्थापना २००८ मध्ये काळा मसाला आणि भडंगपासून झाली. आम्ही यशस्वीरित्या १८+ वर्षे पूर्ण केली आहेत आणि आमची उत्पादन श्रेणी सतत वाढवत आहोत.",
  },
  {
    id: 10,
    category: "business",
    question: "Are your products FSSAI certified?",
    answer:
      "Yes. All our products are manufactured under FSSAI License No. 21520277000803, ensuring complete food safety and quality compliance.",
    questionMarathi: "तुमची उत्पादने FSSAI प्रमाणित आहेत का?",
    answerMarathi:
      "हो. आमची सर्व उत्पादने FSSAI परवाना क्र. 21520277000803 अंतर्गत तयार केली जातात, ज्यामुळे संपूर्ण अन्न सुरक्षा आणि गुणवत्तेची हमी मिळते.",
  },
];

export const chatbotResponses: Record<string, string> = {
  hello: "Namaste! 🙏 Welcome to Bhagwati Industry & Marketing. How can I help you today? You can ask about our products, ordering, delivery, or pricing.",
  hi: "Namaste! 🙏 Welcome to Bhagwati Industry & Marketing. How can I help you today?",
  products: "We offer 50+ products across 6 categories:\n🌾 Flours & Mixes (Thalipeeth, Chakali, Upvas Bhajani, Multigrain etc.)\n🌶️ Chutneys (Peanut, Sesame, Flaxseed, Coconut, Garlic)\n🌿 Mukhwas (Sauf, Til, Elaichi, Premium blends)\n🍯 Sweets (Besan Ladoo, Balu Shahi, Karanji, Chikki)\n🍿 Snacks (Bhadang, Chivda, Masala Shengdana)\n🫙 Masalas (Kala Masala, Goda Masala, Chai Masala)",
  order: "To place an order:\n📞 Call/WhatsApp: +91 9307240577\n📧 Use the Contact form on our website\n📍 Visit: Gat No. 88, Satara Parisar, Aurangabad\n\nWe deliver within Aurangabad and ship across Maharashtra!",
  price: "Our products are very affordable:\n• Chutneys from ₹30 (100g)\n• Flours from ₹45 (200g)\n• Mukhwas ₹40 (100g)\n• Bhadang ₹60 (200g)\n• Sweets from ₹70 (500g)\n\nVisit our Products page for full pricing.",
  delivery: "We deliver within Aurangabad city. For outstation orders across Maharashtra, please call us on +91 9307240577 to arrange shipping.",
  fasting: "Our fasting-friendly products include:\n• Upvas Bhajani (Rajgira, Sabudana, Bhagar, Jeera)\n• Bhagar Pith\n• Rajgira Pith\n• Shabudana Pith\n• Singhara Pith (Water Chestnut)\n• Shengdana Upvas Chatni (no garlic/onion)\n\nAll are free from garlic and onion!",
  "shelf life": "Shelf life varies:\n• Flours: 3–6 months\n• Chutneys: 2–6 months\n• Mukhwas: 6 months\n• Sweets: 1–2 months\n• Masalas: 6–12 months",
  contact: "You can reach us at:\n📞 +91 9307240577\n📍 Gat No. 88, Satara Parisar, Aurangabad (Maha.)\n🕒 Monday–Saturday, 9 AM – 6 PM",
  fssai: "Yes! All our products are manufactured under FSSAI License No. 21520277000803, ensuring complete food safety and quality compliance.",
  natural: "All Bhagwati products are made from 100% natural ingredients with NO artificial preservatives, colours or additives. We maintain strict hygiene throughout manufacturing.",
  gift: "Yes! We offer special gift packs including Karanji, Balu Shahi, Premium Mukhwas and curated hampers – perfect for Diwali, weddings and corporate gifting. Call +91 9307240577 for custom hampers.",
  bulk: "We offer wholesale pricing for bulk orders. Please contact us on +91 9307240577 or use the Contact form to discuss quantities and special pricing.",
  default: "I'm not sure about that. For specific queries, please call us on +91 9307240577 or use the Contact form. You can also browse our Products and FAQ pages for more information! 😊",
};
